const http=require("http"),fs=require("fs"),path=require("path");
const PORT=process.env.PORT||10000;
const html=fs.readFileSync(path.join(__dirname,"telecom-live","index.html"),"utf8");
const json=(res,code,obj)=>{res.writeHead(code,{"content-type":"application/json","cache-control":"no-store","access-control-allow-origin":"*"});res.end(JSON.stringify(obj));};
async function body(req){let s="";for await(const c of req)s+=c;try{return JSON.parse(s||"{}")}catch{return {}}}
async function bankr(prompt){if(!process.env.BANKR_API_KEY)throw Error("bankr_api_key_not_configured");const r=await fetch("https://api.bankr.bot/agent/prompt",{method:"POST",headers:{"content-type":"application/json","X-API-Key":process.env.BANKR_API_KEY},body:JSON.stringify({prompt})});const j=await r.json().catch(()=>({}));if(!r.ok)throw Error("bankr_request_failed");return j}
async function providerProvision(plan,data){const key=process.env.ESIM_PROVIDER_API_KEY||"";const base=(process.env.ESIM_PROVIDER_BASE_URL||"").replace(/\/$/,"");if(plan==="esim"&&!key)return {status:"provider_required",message:"Authorized eSIM/RSP credentials are required for real profile provisioning."};if(plan==="physical"&&!process.env.CARRIER_FULFILLMENT_API_KEY)return {status:"fulfillment_provider_required",message:"Authorized SIM fulfillment credentials are required for shipment."};if(plan==="esim"){const r=await fetch(base+"/esims",{method:"POST",headers:{"content-type":"application/json","authorization":"Bearer "+key},body:JSON.stringify({planId:process.env.ESIM_PLAN_ID||"standard-esim",quantity:1,eid:data.eid||undefined,reference:data.reference})});return {status:r.status,provider_response:await r.json().catch(()=>({}))}}return {status:"paid_pending_fulfillment"} }
const server=http.createServer(async(req,res)=>{const u=new URL(req.url,"http://localhost");
if(req.method==="GET"&&(u.pathname==="/"||u.pathname==="/telecom"||u.pathname==="/index.html")){res.writeHead(200,{"content-type":"text/html;charset=utf-8","cache-control":"no-store"});return res.end(html)}
if(req.method==="GET"&&u.pathname==="/health")return json(res,200,{ok:true,service:"StellarNet 8G+ Quantum Telcom",version:"1.1",network:"Base",chain_id:8453});
if(req.method==="GET"&&u.pathname==="/api/readiness")return json(res,200,{ok:true,bankr:Boolean(process.env.BANKR_API_KEY),merchant:Boolean(process.env.TOKEN_MERCHANT_ADDRESS),esim_provider:Boolean(process.env.ESIM_PROVIDER_API_KEY&&process.env.ESIM_PROVIDER_BASE_URL),physical_fulfillment:Boolean(process.env.CARRIER_FULFILLMENT_API_KEY&&process.env.CARRIER_FULFILLMENT_BASE_URL),carrier_authorized:process.env.CARRIER_MODE==="production_authorized",activation_usd:4,monthly_usd:4,note:"Real cellular activation requires authorized carrier/RSP infrastructure."});
if(req.method==="POST"&&u.pathname==="/api/activate"){const d=await body(req);const plan=d.plan==="physical"?"physical":"esim";if(!process.env.TOKEN_MERCHANT_ADDRESS)return json(res,503,{ok:false,error:"merchant_address_not_configured"});try{const prompt="For StellarNet Telecom, execute exactly one $4 Base Mainnet activation payment to merchant "+process.env.TOKEN_MERCHANT_ADDRESS+". Do not use unlimited approvals. This is a telecom service activation for "+plan+". Return transaction hash and job details.";const b=await bankr(prompt);const p=await providerProvision(plan,{...d,reference:b.jobId||("stellarnet-"+Date.now())});return json(res,202,{ok:true,status:"payment_submitted",plan,amount_usd:4,bankr:b,provisioning:p,next:"Only treat service as active after confirmed on-chain settlement and authorized carrier/RSP confirmation."})}catch(e){return json(res,503,{ok:false,error:e.message})}}
json(res,404,{ok:false,error:"not_found"})});server.listen(PORT,"0.0.0.0",()=>console.log("StellarNet 8G+ Quantum Telcom on "+PORT));