const http=require("http"),fs=require("fs"),path=require("path"),crypto=require("crypto");
const Stripe=require("stripe");
const PORT=process.env.PORT||10000;
const {detectDevice}=require("./carrier/esim-capacity.cjs");
const html=fs.readFileSync(path.join(__dirname,"telecom-live","index.html"),"utf8");
const activationJobs=new Map();
const stripe=process.env.STRIPE_SECRET_KEY?new Stripe(process.env.STRIPE_SECRET_KEY):null;
const json=(res,code,obj)=>{res.writeHead(code,{"content-type":"application/json","cache-control":"no-store","access-control-allow-origin":"*"});res.end(JSON.stringify(obj));};
async function readBody(req){let s="";for await(const c of req)s+=c;return s}
function encrypt(v){if(!v)return "";const key=Buffer.from(process.env.DEVICE_DATA_KEY||"","hex");if(key.length!==32)throw Error("device_data_key_not_configured");const iv=crypto.randomBytes(12),tag=Buffer.alloc(16),cipher=crypto.createCipheriv("aes-256-gcm",key,iv);const enc=Buffer.concat([cipher.update(String(v),"utf8"),cipher.final()]);return Buffer.concat([iv,cipher.getAuthTag(),enc]).toString("base64url")}
function decrypt(v){if(!v)return "";const key=Buffer.from(process.env.DEVICE_DATA_KEY||"","hex");if(key.length!==32)throw Error("device_data_key_not_configured");const b=Buffer.from(v,"base64url"),iv=b.subarray(0,12),tag=b.subarray(12,28),enc=b.subarray(28);const d=crypto.createDecipheriv("aes-256-gcm",key,iv);d.setAuthTag(tag);return Buffer.concat([d.update(enc),d.final()]).toString("utf8")}
async function citrus(pathname,options={}){const key=process.env.ESIM_PROVIDER_API_KEY;if(!key)throw Error("citrus_api_key_not_configured");const base=(process.env.ESIM_PROVIDER_BASE_URL||"https://citrusmobile.com/api/v2/reseller").replace(/\/$/,"");const r=await fetch(base+pathname,{...options,headers:{"content-type":"application/json","authorization":"Bearer "+key,...(options.headers||{})}});const text=await r.text();let data;try{data=JSON.parse(text)}catch{data={raw:text}}if(!r.ok)throw Error("citrus_http_"+r.status);return data}
async function provisionAfterPayment(job,sessionId){const label="StellarNet "+job.id;const p=await citrus("/esim/provision",{method:"POST",body:JSON.stringify({end_user_reference:job.id,label})});let fund=null,enabled=null;if(p.iccid){fund=await citrus("/esim/"+encodeURIComponent(p.iccid)+"/fund",{method:"POST",body:JSON.stringify({amount:Number(process.env.INITIAL_DATA_WALLET_USD||4)})});try{enabled=await citrus("/esim/"+encodeURIComponent(p.iccid)+"/enable",{method:"POST"})}catch(e){enabled={error:e.message}}}job.status="provisioned";job.iccid=p.iccid||null;job.install_url=p.direct_install_url||null;job.qr_code=p.qr_code||null;job.provider=p;job.funding=fund;job.enabled=enabled;job.stripe_session_id=sessionId;job.updatedAt=new Date().toISOString();activationJobs.set(job.id,job);if(stripe&&sessionId){try{const s=await stripe.checkout.sessions.retrieve(sessionId);if(s.subscription){await stripe.subscriptions.update(s.subscription,{metadata:{stellarnet_activation_id:job.id,iccid:job.iccid||""}})}}catch(e){job.stripe_metadata_error=e.message}}return job}
async function createCheckout(d){if(!stripe)throw Error("stripe_not_configured");const activationId="act-"+Date.now()+"-"+crypto.randomBytes(4).toString("hex");const job={id:activationId,status:"checkout_created",plan:"esim",device_id:String(d.device_id||""),eid_encrypted:encrypt(d.eid||""),createdAt:new Date().toISOString()};activationJobs.set(activationId,job);const origin=process.env.PUBLIC_BASE_URL||"https://stellarnet-8g-plus-quantum-telecom.onrender.com";const session=await stripe.checkout.sessions.create({mode:"subscription",line_items:[{price:process.env.STRIPE_ACTIVATION_PRICE_ID||"price_1UMfb9RPRXTyZSXkpgUdtc37",quantity:1},{price:process.env.STRIPE_MONTHLY_PRICE_ID||"price_1UMfb8RPRXTyZSXkvkRl3QC3",quantity:1}],client_reference_id:activationId,customer_creation:"always",phone_number_collection:{enabled:true},subscription_data:{metadata:{stellarnet_activation_id:activationId},billing_mode:{type:"flexible"}},metadata:{stellarnet_activation_id:activationId,plan:"esim"},success_url:origin+"/?activated=1&session_id={CHECKOUT_SESSION_ID}",cancel_url:origin+"/?cancelled=1"});job.checkout_url=session.url;job.stripe_session_id=session.id;activationJobs.set(activationId,job);return {ok:true,id:activationId,url:session.url,amount_usd:12,monthly_usd:4}}
async function handleStripeEvent(event){if(event.type==="checkout.session.completed"||event.type==="checkout.session.async_payment_succeeded"){const s=event.data.object;if(s.payment_status!=="paid"&&event.type==="checkout.session.completed")return;const id=s.metadata?.stellarnet_activation_id||s.client_reference_id;const job=activationJobs.get(id);if(!job)return;job.status="payment_confirmed";job.payment_status=s.payment_status;activationJobs.set(id,job);try{await provisionAfterPayment({...job,eid:decrypt(job.eid_encrypted)},s.id)}catch(e){job.status="provisioning_error";job.error=e.message;activationJobs.set(id,job)}}
if(event.type==="invoice.paid"){const inv=event.data.object;const sub=inv.subscription;if(sub&&stripe){try{const ss=await stripe.subscriptions.retrieve(sub);const id=ss.metadata?.stellarnet_activation_id;const job=activationJobs.get(id);if(job){job.subscription_status=ss.status;job.last_invoice_paid=inv.id;activationJobs.set(id,job)}}catch{}}}
if(event.type==="invoice.payment_failed"||event.type==="customer.subscription.deleted"){const obj=event.data.object;const subId=obj.subscription||obj.id;if(stripe&&subId){try{const ss=await stripe.subscriptions.retrieve(subId);const id=ss.metadata?.stellarnet_activation_id;const job=activationJobs.get(id);if(job&&job.iccid){try{await citrus("/esim/"+encodeURIComponent(job.iccid)+"/disable",{method:"POST"})}catch{}job.status=event.type==="invoice.payment_failed"?"billing_failed":"cancelled";job.subscription_status=ss.status;activationJobs.set(id,job)}}catch{}}}}
const server=http.createServer(async(req,res)=>{const u=new URL(req.url,"http://localhost");
if(req.method==="POST"&&u.pathname==="/stripe/webhook"){const raw=await readBody(req);if(!stripe||!process.env.STRIPE_WEBHOOK_SECRET)return json(res,503,{ok:false,error:"stripe_webhook_not_configured"});let event;try{event=stripe.webhooks.constructEvent(raw,req.headers["stripe-signature"],process.env.STRIPE_WEBHOOK_SECRET)}catch(e){return json(res,400,{ok:false,error:"invalid_webhook_signature"})}try{await handleStripeEvent(event);return json(res,200,{received:true})}catch(e){return json(res,500,{ok:false,error:"webhook_processing_failed"})}}
if(req.method==="GET"&&(u.pathname==="/"||u.pathname==="/telecom"||u.pathname==="/index.html")){res.writeHead(200,{"content-type":"text/html;charset=utf-8","cache-control":"no-store"});return res.end(html)}
if(req.method==="GET"&&u.pathname==="/health")return json(res,200,{ok:true,service:"StellarNet 8G+ Quantum Telcom",version:"2.0",network:"Base",chain_id:8453});
if(req.method==="GET"&&u.pathname==="/api/readiness")return json(res,200,{ok:true,bankr:Boolean(process.env.BANKR_API_KEY),stripe:Boolean(process.env.STRIPE_SECRET_KEY&&process.env.STRIPE_WEBHOOK_SECRET),stripe_prices:Boolean(process.env.STRIPE_ACTIVATION_PRICE_ID&&process.env.STRIPE_MONTHLY_PRICE_ID),esim_provider:Boolean(process.env.ESIM_PROVIDER_API_KEY),provider_base:Boolean(process.env.ESIM_PROVIDER_BASE_URL),monthly_usd:4,activation_usd:12,initial_data_wallet_usd:Number(process.env.INITIAL_DATA_WALLET_USD||4),accepted_base_assets:23,note:"$12 activation plus $4/month; initial data wallet is separate provider-funded connectivity credit. Actual cellular availability depends on supported carrier/eSIM coverage."});
if(req.method==="POST"&&u.pathname==="/api/device-check"){const d=JSON.parse((await readBody(req))||"{}");return json(res,200,{ok:true,device:detectDevice(d)})}
if(req.method==="POST"&&u.pathname==="/api/activate"){try{const d=JSON.parse((await readBody(req))||"{}");if(d.plan==="physical")return json(res,400,{ok:false,error:"physical_sim_not_enabled_in_this_release"});return json(res,200,await createCheckout(d))}catch(e){return json(res,503,{ok:false,error:e.message})}}
if(req.method==="GET"&&u.pathname==="/api/activation-status"){const id=u.searchParams.get("id"),job=activationJobs.get(id);return job?json(res,200,{ok:true,id:job.id,status:job.status,install_url:job.install_url||null,iccid:job.iccid||null,subscription_status:job.subscription_status||null}):json(res,404,{ok:false,error:"activation_not_found"})}
if(req.method==="GET"&&u.pathname==="/api/private-activation"){if(u.searchParams.get("token")!==process.env.PRIVATE_ACTIVATION_TOKEN)return json(res,404,{ok:false,error:"not_found"});return json(res,200,{ok:true,private:true,service:"StellarNet eSIM activation",instructions:"POST the EID to this endpoint with the same token to provision the authorized private line."})}
if(req.method==="POST"&&u.pathname==="/api/private-activation"){if(req.headers["x-private-token"]!==process.env.PRIVATE_ACTIVATION_TOKEN)return json(res,404,{ok:false,error:"not_found"});try{const d=JSON.parse((await readBody(req))||"{}");const p=await citrus("/esim/provision",{method:"POST",body:JSON.stringify({end_user_reference:"private-"+Date.now(),label:"StellarNet Private Line"})});let fund=null,enabled=null;if(p.iccid){fund=await citrus("/esim/"+encodeURIComponent(p.iccid)+"/fund",{method:"POST",body:JSON.stringify({amount:Number(process.env.INITIAL_DATA_WALLET_USD||4)})});try{enabled=await citrus("/esim/"+encodeURIComponent(p.iccid)+"/enable",{method:"POST"})}catch{}}return json(res,200,{ok:true,install_url:p.direct_install_url||null,qr_code:p.qr_code||null,iccid:p.iccid||null,funding:fund,enabled})}catch(e){return json(res,503,{ok:false,error:e.message})}}
json(res,404,{ok:false,error:"not_found"})});
server.listen(PORT,"0.0.0.0",()=>console.log("StellarNet 8G+ Quantum Telcom v2 on "+PORT));