import http from "node:http";import fs from "node:fs";import path from "node:path";import {fileURLToPath} from "node:url";
const __dirname=path.dirname(fileURLToPath(import.meta.url));const PORT=process.env.PORT||10000;
import {createRequire} from "node:module";const require=createRequire(import.meta.url);
const {detectDevice,readiness:createEsimReadiness}=require("./carrier/esim-capacity.cjs");
const {authorizeTransmission}=require("./carrier/authority-registry.cjs");
const {readiness:scaleReadiness,LIMITS}=require("./carrier/scale-gates.cjs");
const activationJobs=new Map();
const CAPACITY={profiles:"unlimited-software-orchestrated",simultaneousProvisioning:"provider/RSP limited",radioCapacity:"licensed-RAN limited",interconnect:"carrier-agreement limited",mode:"fail-closed"};
const PRICING={setupUsd:12,monthlyPlatformUsd:4,dataMarkupPct:Number(process.env.DATA_MARKUP_PCT||35),includedDataCreditUsd:Number(process.env.INCLUDED_DATA_CREDIT_USD||0)};
const html=fs.readFileSync(path.join(__dirname,"telecom-live","index.html"),"utf8");
const envBool=k=>String(process.env[k]||"").toLowerCase()==="true";
const json=(res,code,obj)=>{res.writeHead(code,{"content-type":"application/json","cache-control":"no-store","access-control-allow-origin":"*"});res.end(JSON.stringify(obj));};
async function body(req){let s="";for await(const c of req)s+=c;try{return JSON.parse(s||"{}")}catch{return {}}}
async function bankr(prompt){if(!process.env.BANKR_API_KEY)throw Error("bankr_api_key_not_configured");const r=await fetch("https://api.bankr.bot/agent/prompt",{method:"POST",headers:{"content-type":"application/json","X-API-Key":process.env.BANKR_API_KEY},body:JSON.stringify({prompt})});const j=await r.json().catch(()=>({}));if(!r.ok)throw Error("bankr_request_failed");return j}
function authority(){return{carrierMode:process.env.CARRIER_MODE||"sandbox",carrierAuthorized:process.env.CARRIER_MODE==="production_authorized",spectrumEvidence:Boolean(process.env.SPECTRUM_AUTHORITY_EVIDENCE_HASH),spectrumExpiresAt:process.env.SPECTRUM_AUTHORITY_EXPIRES_AT||null,interconnectAuthorized:envBool("INTERCONNECT_AUTHORIZED"),equipmentCertified:envBool("EQUIPMENT_CERTIFIED"),rspProductionAuthorized:envBool("RSP_PRODUCTION_AUTHORIZED"),gsmaProductionCert:envBool("GSMA_PRODUCTION_CERT"),sasSmAccredited:envBool("SAS_SM_ACCREDITED"),regulatoryReviewComplete:envBool("REGULATORY_REVIEW_COMPLETE")}}
function transmissionGate(d){const a=authority();const frequency=Number(d.frequencyHz);const right={id:"runtime",status:"AUTHORIZED",startHz:Number(process.env.AUTHORIZED_START_HZ||0),endHz:Number(process.env.AUTHORIZED_END_HZ||0),evidenceHash:process.env.SPECTRUM_AUTHORITY_EVIDENCE_HASH||"",expiresAt:process.env.SPECTRUM_AUTHORITY_EXPIRES_AT||null};const frequencyCovered=Number.isFinite(frequency)&&authorizeTransmission([right],frequency);const allowed=a.carrierAuthorized&&a.interconnectAuthorized&&a.equipmentCertified&&a.regulatoryReviewComplete&&frequencyCovered&&a.rspProductionAuthorized&&a.gsmaProductionCert&&a.sasSmAccredited;return{allowed,checks:{carrier:a.carrierAuthorized,interconnect:a.interconnectAuthorized,equipment:a.equipmentCertified,regulatory:a.regulatoryReviewComplete,spectrum:frequencyCovered,rsp:a.rspProductionAuthorized,gsma:a.gsmaProductionCert,sasSm:a.sasSmAccredited}}}
async function citrus(path,method="GET",payload){const key=process.env.ESIM_PROVIDER_API_KEY||"";const base=(process.env.ESIM_PROVIDER_BASE_URL||"https://citrusmobile.com/api/v2/reseller").replace(/\/$/,"");const r=await fetch(base+path,{method,headers:{"content-type":"application/json",authorization:"Bearer "+key},body:payload?JSON.stringify(payload):undefined});return{status:r.status,data:await r.json().catch(()=>({}))};}
async function providerProvision(plan,data){const key=process.env.ESIM_PROVIDER_API_KEY||"";const type=process.env.ESIM_PROVIDER_TYPE||"generic";const base=(process.env.ESIM_PROVIDER_BASE_URL||"").replace(/\/$/,"");if(plan==="esim"&&!key)return{status:"provider_required",message:"Authorized eSIM/RSP credentials are required for real profile provisioning."};if(plan==="physical"&&!process.env.CARRIER_FULFILLMENT_API_KEY)return{status:"fulfillment_provider_required",message:"Authorized SIM fulfillment credentials are required for shipment."};if(plan==="esim"){if(type==="citrus"){const p=await citrus("/esim/provision","POST",{end_user_reference:data.reference||"stellarnet-activation",label:data.label||"StellarNet customer"});if(p.status!==201)return{status:p.status,provider:"citrus",provider_response:p.data};const iccid=p.data?.iccid;if(!iccid)return{status:502,provider:"citrus",provider_response:p.data,error:"citrus_missing_iccid"};const initialFund=Number(process.env.CITRUS_INITIAL_FUND_USD||0);let funded=null,enabled=null;if(initialFund>0){funded=await citrus("/esim/"+encodeURIComponent(iccid)+"/fund","POST",{amount:initialFund});if(funded.status!==200)return{status:502,provider:"citrus",provider_response:p.data,funding:funded,error:"citrus_funding_failed"}}if(process.env.CITRUS_AUTO_ENABLE==="true"){enabled=await citrus("/esim/"+encodeURIComponent(iccid)+"/enable","POST");if(enabled.status!==200)return{status:502,provider:"citrus",provider_response:p.data,funding:funded,enable:enabled,error:"citrus_enable_failed"}}return{status:200,provider:"citrus",provider_response:p.data,funding:funded,enable:enabled,pricing:PRICING}}const r=await fetch(base+"/esims",{method:"POST",headers:{"content-type":"application/json","authorization":"Bearer "+key},body:JSON.stringify({planId:process.env.ESIM_PLAN_ID||"standard-esim",quantity:1,eid:data.eid||undefined,reference:data.reference})});return{status:r.status,provider_response:await r.json().catch(()=>({}))}}return{status:"paid_pending_fulfillment"}}
const server=http.createServer(async(req,res)=>{const u=new URL(req.url,"http://localhost");
if(req.method==="GET"&&(u.pathname==="/"||u.pathname==="/telecom"||u.pathname==="/index.html")){res.writeHead(200,{"content-type":"text/html;charset=utf-8","cache-control":"no-store"});return res.end(html)}
if(req.method==="GET"&&u.pathname==="/health")return json(res,200,{ok:true,service:"StellarNet 8G+ Quantum Telcom",version:"1.3",network:"Base",chain_id:8453});
if(req.method==="GET"&&u.pathname==="/api/capacity")return json(res,200,{ok:true,capacity:CAPACITY,scale:scaleReadiness(),target_subscribers:LIMITS.targetSubscribers,subscriberControl:"ready",billingEntitlement:"ready",devicePolicy:"ready",telemetry:"ready",esimOrchestration:"ready",physicalSimFulfillment:"adapter-ready",ran:"requires-authorized-radio-network",interconnect:"requires-authorized-carrier",note:"Software capacity can scale control-plane records, but real subscriber throughput is bounded by authorized RAN, spectrum, interconnect and RSP capacity."});
if(req.method==="GET"&&u.pathname==="/api/authority")return json(res,200,{ok:true,authority:authority(),policy:"No payment, token, patent, or on-chain record grants spectrum authority. Transmission requires every production gate."});
if(req.method==="GET"&&u.pathname==="/api/pricing")return json(res,200,{ok:true,pricing:PRICING,model:"setup + platform subscription + metered data",marginProtection:"The $4 platform fee is not an unlimited-data promise. Data should be sold from provider cost/rates plus the configured markup.",note:"Actual profitability varies by country/network wholesale rate, taxes, payment fees, refunds and usage."});
if(req.method==="GET"&&u.pathname==="/api/readiness"){const a=authority();return json(res,200,{ok:true,bankr:Boolean(process.env.BANKR_API_KEY),merchant:Boolean(process.env.TOKEN_MERCHANT_ADDRESS),esim_provider:Boolean(process.env.ESIM_PROVIDER_API_KEY&&process.env.ESIM_PROVIDER_BASE_URL),physical_fulfillment:Boolean(process.env.CARRIER_FULFILLMENT_API_KEY&&process.env.CARRIER_FULFILLMENT_BASE_URL),carrier_authorized:a.carrierAuthorized,setup_usd:PRICING.setupUsd,activation_usd:PRICING.setupUsd,monthly_usd:PRICING.monthlyPlatformUsd,esim:createEsimReadiness({carrierAuthorized:a.carrierAuthorized,rspConfigured:Boolean(process.env.ESIM_PROVIDER_API_KEY&&process.env.ESIM_PROVIDER_BASE_URL),device:{esim_capable:true}}),production_gates:a,note:"Payment completion starts activation; RF transmission remains denied until every real carrier, spectrum, interconnect, equipment, regulatory, RSP and GSMA gate passes."})}
if(req.method==="POST"&&u.pathname==="/api/device-check"){const d=await body(req);return json(res,200,{ok:true,device:detectDevice(d)});}
if(req.method==="GET"&&u.pathname==="/api/activation-status"){const id=u.searchParams.get("id");const job=activationJobs.get(id);return job?json(res,200,{ok:true,...job}):json(res,404,{ok:false,error:"activation_not_found"});}
if(req.method==="POST"&&u.pathname==="/api/activate"){const d=await body(req);const plan=d.plan==="physical"?"physical":"esim";if(!process.env.TOKEN_MERCHANT_ADDRESS)return json(res,503,{ok:false,error:"merchant_address_not_configured"});const id="act-"+Date.now()+"-"+Math.random().toString(36).slice(2,8);try{const b=await bankr("For StellarNet Telecom, execute exactly one $12 Base Mainnet setup payment to merchant "+process.env.TOKEN_MERCHANT_ADDRESS+". Do not use unlimited approvals. This is a telecom service activation for "+plan+". Return transaction hash, confirmation status, and job details.");const txHash=b.txHash||b.transactionHash||b.hash||b.transaction?.hash||null;const confirmed=Boolean(b.confirmed===true||b.status==="confirmed"||b.transaction?.confirmed===true);const a=authority();const rspConfigured=Boolean(process.env.ESIM_PROVIDER_API_KEY&&process.env.ESIM_PROVIDER_BASE_URL);const device=detectDevice(d);const gate=transmissionGate(d);activationJobs.set(id,{id,status:confirmed?"payment_confirmed":"payment_pending",plan,amount_usd:PRICING.setupUsd,monthly_usd:PRICING.monthlyPlatformUsd,txHash,bankr:b,device,authority:a,rsp_configured:rspConfigured,transmission_permitted:false,createdAt:new Date().toISOString()});if(confirmed){const p=await providerProvision(plan,{...d,reference:b.jobId||id});const finalRf=gate.allowed&&(plan==="physical"||rspConfigured)&& (plan==="physical"||device.esim_capable);activationJobs.set(id,{...activationJobs.get(id),status:p.status===200||p.status==="paid_pending_fulfillment"?"provisioning_started":"provisioning_pending",provisioning:p,transmission_permitted:finalRf,transmission_gate:gate});}return json(res,202,{ok:true,id,...activationJobs.get(id),next:confirmed?"Payment is confirmed; provisioning begins automatically. RF transmission remains denied unless every real authorization and certification gate passes.":"Waiting for payment confirmation before provisioning."})}catch(e){activationJobs.set(id,{id,status:"payment_error",error:e.message});return json(res,503,{ok:false,id,error:e.message})}}
json(res,404,{ok:false,error:"not_found"})});server.listen(PORT,"0.0.0.0",()=>console.log("StellarNet 8G+ Quantum Telcom on "+PORT));