plugins { id 'com.android.application' }
android {
    namespace 'com.stellarnet.telecom'
    compileSdk 36
    defaultConfig {
        applicationId 'com.stellarnet.telecom'
        minSdk 23
        targetSdk 36
        versionCode 1
        versionName '1.0.0'
    }
    buildTypes {
        debug { applicationIdSuffix '.debug' }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}
